name: MLflow CI

on:
  push:
    branches: [ main ]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-python-version: 3.10

      - name: Install dependencies
        run: |
          conda install -y pip
          pip install mlflow

      - name: Run MLflow Project
        run: mlflow run ./MLProject
        shell: bash -l {0}
